<?php
/**
 * Plugin Name: Spillhistorie Article Series Shortcode
 * Description: Adds a shortcode [sh-series] to display an ordered list of articles associated with a specific tag.
 * Version: 1.0
 * Author: Mats Lindh
 * License: Public Domain
 */

// The initial version and skeleton was generated by Gemini Pro 3.0. Further additions and enhancements has been
// made by the author as given above.
//
// The code is thus licensed into the public domain, since it's based on whatever the matrix multiplication auto
// complete machine says a Wordpress plugin should look like.
//
// No warranties provided. Do as you wish. A machine does not know your intent.

// Prevent direct access to the file
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Render the [sh-series] shortcode.
 *
 * @param array $atts User attributes (tag, class).
 * @return string HTML output of the list.
 */
function sh_series_shortcode_handler( $atts ) {
    // 1. Extract and sanitize attributes
    $atts = shortcode_atts(
        array(
            'tag'   => '', // The tag slug to query
            'class' => '', // Custom CSS class
            'title' => '', // Optional title
            'sort' => 'desc',
            'strip_prefix' => '',
        ),
        $atts,
        'sh-series'
    );

    // If no tag is provided, return nothing
    if ( empty( $atts['tag'] ) ) {
        return '';
    }

    $valid_sort_orders = [ 'asc', 'desc' ];

    if ( ! in_array( $atts['sort'], $valid_sort_orders ) ) {
        $atts['sort'] = 'desc';
    }

    // 2. Prepare the CSS classes
    // Sanitize the provided tag to ensure it's a valid CSS identifier
    $clean_tag_slug = sanitize_html_class( $atts['tag'] );
    $tag_class      = 'tag-' . $clean_tag_slug;

    // Sanitize the custom class provided by the user
    $custom_class   = sanitize_html_class( $atts['class'] );

    // Base class for styling + dynamic classes
    $container_classes = trim( "sh-series-box $custom_class $tag_class" );

    $container_tag = 'aside';

    // 3. Query the posts
    $args = array(
        'tag'            => $atts['tag'],   // Queries by tag slug
        'posts_per_page' => -1,             // Get all posts in the series
        'orderby'        => 'date',         // Order by publication date
        'order'          => strtoupper( $atts['sort'] ), // Ascending order (oldest first)
        'post_status'    => 'publish',      // Only published posts
    );

    $query = new WP_Query( $args );

    // 4. Build the Output
    $output = '';

    // Get the current post ID to highlight it in the list
    $current_post_id = get_the_ID();

    if ( $query->have_posts() ) {
        // Start Container
        $output .= '<' . $container_tag . ' class="' . esc_attr( $container_classes ) . '">';

        // Output Title if provided
        if ( ! empty( $atts['title'] ) ) {
            $output .= '<h3 class="sh-series-title">' . esc_html( $atts['title'] ) . '</h3>';
        }

        $output .= '<ol>';

        while ( $query->have_posts() ) {
            $query->the_post();

            // Determine if this item is the current post
            $is_current = ( get_the_ID() === $current_post_id );
            $li_class   = $is_current ? ' class="current-series-item"' : '';

            $title = get_the_title();

            if (
                $atts['strip_prefix'] &&
                ( substr( $title, 0, strlen( $atts['strip_prefix'] ) ) == $atts['strip_prefix'] )
            ) {
                $title = substr( $title, strlen( $atts['strip_prefix'] ) );
            }

            // List Item with Link
            $output .= '<li' . $li_class . '>';
            $output .= !$is_current ? ('<a href="' . get_permalink() . '">' . $title . '</a>') : $title;
            $output .= '</li>';
        }

        $output .= '</ol>';
        $output .= '</' . $container_tag . '>'; // End Container

        // Restore original Post Data
        wp_reset_postdata();
    }

    return $output;
}
add_shortcode( 'sh-series', 'sh_series_shortcode_handler' );

/**
 * Register the dedicated Gutenberg block.
 */
function sh_series_register_block() {
    // Register the JavaScript for the block
    wp_register_script(
        'sh-series-block-script',
        plugins_url( 'sh-article-series-block.js', __FILE__ ),
        array( 'wp-blocks', 'wp-element', 'wp-editor', 'wp-components' ), // Dependencies
        filemtime( plugin_dir_path( __FILE__ ) . 'sh-article-series-block.js' )
    );

    // Register the block type
    register_block_type( 'sh-series/list', array(
        'editor_script'   => 'sh-series-block-script',
        'render_callback' => 'sh_series_shortcode_handler', // Reuse the existing handler
        'attributes'      => array(
            'tag'   => array( 'type' => 'string', 'default' => '' ),
            'class' => array( 'type' => 'string', 'default' => '' ),
            'title' => array( 'type' => 'string', 'default' => '' ),
        ),
    ) );
}
add_action( 'init', 'sh_series_register_block' );

/**
 * Enqueue basic styles for the shortcode box.
 * This ensures the "separate box" look is applied by default.
 */
function sh_series_enqueue_styles() {
    $custom_css = "
        .sh-series-box {
            background-color: #f9f9f9;
            border: 1px solid #e5e5e5;
            padding: 15px 20px;
            margin: 20px 0;
            border-radius: 4px;
        }
        .sh-series-box .sh-series-title {
            margin-top: 0;
            margin-bottom: 10px;
            font-size: 1.1em;
            font-weight: 600;
        }
        .sh-series-box ol {
            margin: 0;
            padding-left: 20px;
        }
        .sh-series-box li {
            margin-bottom: 5px;
        }
    ";

    // We inline this to keep the plugin single-file and lightweight
    wp_add_inline_style( 'wp-block-library', $custom_css );
}
// Hook into enqueue_scripts for frontend and enqueue_block_editor_assets for backend editor styling
add_action( 'wp_enqueue_scripts', 'sh_series_enqueue_styles' );
add_action( 'enqueue_block_editor_assets', 'sh_series_enqueue_styles' );